# Generated by Django 2.2.9 on 2020-01-30 02:15

import cidade_ajuda.base.managers
import cidade_ajuda.base.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, verbose_name='Comentário')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data de hora do envio')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='título')),
                ('sugestao_descricao', models.TextField(help_text='Este texto serve como sugestão para ocorrências deste tipo.', max_length=300, verbose_name='sugestão de descrição')),
                ('duracao', models.DurationField(help_text='Use o seguinte formato: DD days, HH:MM:SS', verbose_name='duração')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(validators=[cidade_ajuda.base.validators.MinAgeValidator(18)], verbose_name='data de nascimento')),
                ('quantidade_respostas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantidade de respostas')),
                ('quantidade_respostas_confiaveis', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantidade de respostas confiáveis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', cidade_ajuda.base.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('esta_ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True, help_text='Momento em que a ocorrência foi registrada', verbose_name='data e hora de criação')),
                ('prazo_termino', models.DateTimeField(help_text='prazo para término da ocorrência', verbose_name='prazo')),
                ('transitavel_veiculo', models.BooleanField(verbose_name='transitável por veículo')),
                ('transitavel_a_pe', models.BooleanField(verbose_name='transitável a pé')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('quantidade_existente', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='existentes')),
                ('quantidade_inexistente', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='inexistentes')),
                ('quantidade_caso_encerrado', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='caso encerrado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Tipo', verbose_name='Tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='base.Usuario', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('EX', 'Existente'), ('IN', 'Inexistente'), ('FI', 'Finalizado')], max_length=2, verbose_name='resposta')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data de hora do envio')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Ocorrencia', verbose_name='Ocorrência')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Usuario', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ocorrencias', verbose_name='Imagem')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagens', to='base.Ocorrencia', verbose_name='Ocorrência')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='comentarios', verbose_name='Imagem')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Comentario', verbose_name='Comentário')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Ocorrencia', verbose_name='Ocorrência'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Usuario', verbose_name='Usuário'),
        ),
    ]
